package com.server.view;

import com.server.controller.Server;
import java.awt.Color;
import javax.swing.JFrame;

public class MainFrameServer extends javax.swing.JFrame {

    public MainFrameServer() {
        initComponents();
        init();
    }

    private void init() {
        this.setTitle("Java chat app server");
        this.setLocationRelativeTo(null);
        this.setDefaultLookAndFeelDecorated(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartServer = new javax.swing.JButton();
        lbHeading = new javax.swing.JLabel();
        lbNotification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        btnStartServer.setText("Start server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        lbHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeading.setText("PBL 4: CHAT APP SERVER");

        lbNotification.setBackground(new java.awt.Color(255, 255, 255));
        lbNotification.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNotification.setForeground(new java.awt.Color(255, 0, 0));
        lbNotification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNotification.setText("Click here to start server at PORT 9999");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lbHeading)
                .addGap(77, 77, 77))
            .addComponent(lbNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbHeading)
                .addGap(26, 26, 26)
                .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNotification)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        Thread t = new Thread() {
          public void run() {
              try {
                  new Server();
              } catch (Exception e) {
                  e.printStackTrace();
              }
          }
        };
        
        t.start();
        
        btnStartServer.setEnabled(false);
        lbNotification.setText("Start server successfully.");
        lbNotification.setForeground(Color.GREEN);
    }//GEN-LAST:event_btnStartServerActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JLabel lbHeading;
    private javax.swing.JLabel lbNotification;
    // End of variables declaration//GEN-END:variables
}
